### ISSUE TITLE
APR

### ISSUE THREAD

**Issue by mehmetuken** [Orion07/clientless#1]
Apr de hata mı var hocam?

**Comment by Orion07** [comment]
ne gibi ?

**Comment by mehmetuken** [comment]
Gelen paketi doğru çözmüyo değişiklikmi oldu

**Comment by Orion07** [comment]
bilgim yok en son temmuzda kullandım

**Comment by mehmetuken** [comment]
Anladım teşekkürler son olarak şifrelemeyi exe nin hangi bölümünden elde ettiğinizi kısaca anlatabilirmisiniz?
